query AllSiteUpdates {
  siteUpdates(
    orderBy: [
      {
        title: desc
      }
    ],
    where: {
      publishedAt: {
        gte: "2022-01-01T00:00:00.000Z"
      }
    }
    take: 5
  ) {
    id
    title
    content
    publishedAt
    updatedAt
  }
}

query GetSiteUpdate($id: Int!) {
  siteUpdate(id: $id) {
    id
    title
    content
    publishedAt
    updatedAt
  }
}