# UserSnsの取得
query GetUserSns($id: Int!) {
  userSns(id: $id) {
    id
    userId
    createdAt
    updatedAt
    x
    facebook
    instagram
  }
}

# UserSnsの一覧を取得
query GetUserSnsList {
  userSnsList {
    id
    userId
    createdAt
    updatedAt
    x
    facebook
    instagram
  }
}

# UserSnsの作成
mutation CreateUserSns($data: UserSnsCreateInput!) {
  createUserSns(data: $data) {
    id
    userId
    createdAt
    updatedAt
    x
    facebook
    instagram
  }
}

input UserSnsCreateInput {
  user: UserCreateNestedOneWithoutUserSnsInput!
  x: String
  facebook: String
  instagram: String
}

input UserCreateNestedOneWithoutUserSnsInput {
  connect: UserWhereUniqueInput
}

input UserWhereUniqueInput {
  email: String
}

# UserSnsの更新
mutation UpdateUserSns($id: Int!, $data: UpdateUserSnsInput!) {
  updateUserSns(id: $id, data: $data) {
    id
    userId
    createdAt
    updatedAt
    x
    facebook
    instagram
  }
}
