# UserProfileの取得
query GetUserProfile($id: Int!) {
  userProfile(id: $id) {
    id
    userId
    shopMstCode
    catchphrase
    introduction
    createdAt
    updatedAt
  }
}

# UserProfileの一覧を取得
query GetUserProfileList {
  userProfiles {
    id
    userId
    shopMstCode
    catchphrase
    introduction
    createdAt
    updatedAt
  }
}

# UserProfileの作成
mutation CreateUserProfile($data: CreateUserProfileInput!) {
  createUserProfile(data: $data) {
    id
    userId
    shopMstCode
    catchphrase
    introduction
    createdAt
    updatedAt
  }
}

input CreateUserProfileInput {
  user: UserCreateNestedOneWithoutUserProfileInput!
  shopMst: ShopMstCreateNestedOneWithoutUserProfilesInput
  catchphrase: String
  introduction: String
}

input UserCreateNestedOneWithoutUserProfileInput {
  connect: UserWhereUniqueInput
}

input UserWhereUniqueInput {
  email: String
}

input ShopMstCreateNestedOneWithoutUserProfilesInput {
  connect: ShopMstWhereUniqueInput
}

input ShopMstWhereUniqueInput {
  code: String
}

# UserProfileの更新
mutation UpdateUserProfile($id: Int!, $data: UpdateUserProfileInput!) {
  updateUserProfile(id: $id, data: $data) {
    id
    userId
    shopMstCode
    catchphrase
    introduction
    createdAt
    updatedAt
  }
}

input UpdateUserProfileInput {
  catchphrase: String
  introduction: String
  shopMst: ShopMstUpdateOneWithoutUserProfilesInput
}

input ShopMstUpdateOneWithoutUserProfilesInput {
  connect: ShopMstConnectInput
}

input ShopMstConnectInput {
  code: String
}