# users.gql

scalar DateTime
scalar Upload

type User {
  id: Int!
  name: String!
  email: String!
  isDeleted: Boolean!
  createdAt: DateTime!
  updatedAt: DateTime!
  userImageFile: String
}

input UserCreateInput {
  name: String!
  email: String!
  password: String!
  isDeleted: Boolean
  createdAt: DateTime
  updatedAt: DateTime
}

input SignInUserArgs {
  email: String!
  password: String!
}

type CodeMsg {
  statusCode: Int!
  message: String!
}

type Token {
  token: String!
}

type Query {
  user(id: Int!): User
  dummyUser(id: Int!): User
  isUserLoggedIn: Boolean!
}

type Mutation {
  createUser(data: UserCreateInput!): User!
  signIn(data: SignInUserArgs!): Token!
  signOut: CodeMsg!
  updateUser(id: Int!, data: UserUpdateInput!): User!
  uploadUserImage(id: Int!, file: Upload!): Boolean
}

# ログイン中ユーザの情報を取得
query GetCurrentUser {
  currentUser {
    id
    name
    email
    isDeleted
    createdAt
    updatedAt
    userImageFile
    userSns {
      id
      x
      facebook
      instagram
    }
    userProfile {
      id
      shopMstCode
      catchphrase
      introduction
    }
  }
}

input UserUpdateInput {
  name: String
}

# ユーザ情報の更新
mutation UpdateUser($id: Int!, $data: UserUpdateInput!) {
  updateUser(id: $id, data: $data) {
    id
    name
    email
    isDeleted
    createdAt
    updatedAt
    userImageFile
    userSns {
      id
      x
      facebook
      instagram
    }
    userProfile {
      id
      shopMstCode
      catchphrase
      introduction
    }
  }
}

# Userの情報を取得
query GetUser($id: Int!) {
  user(id: $id) {
    id
    name
    email
    isDeleted
    createdAt
    updatedAt
    userImageFile
    userSns {
      id
      x
      facebook
      instagram
    }
    userProfile {
      id
      shopMstCode
      catchphrase
      introduction
    }
  }
}